/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type UserRole = { 'admin': null } | { 'user': null } | { 'guest': null };
export type PassStatus = { 'Pending': null } | { 'Approved': null } | { 'Rejected': null } | { 'Exited': null } | { 'Returned': null };
export interface GatePass {
  id: bigint;
  studentName: string;
  studentId: string;
  rollNumber: string;
  department: string;
  purpose: string;
  destination: string;
  expectedReturnTime: string;
  note: string;
  status: PassStatus;
  requestedAt: bigint;
  approvedAt: [] | [bigint];
  exitedAt: [] | [bigint];
  returnedAt: [] | [bigint];
  rejectionReason: [] | [string];
  requester: Principal;
}
export interface LogEntry {
  passId: bigint;
  studentName: string;
  rollNumber: string;
  action: string;
  timestamp: bigint;
}
export interface Stats {
  total: bigint;
  pending: bigint;
  approved: bigint;
  rejected: bigint;
  exited: bigint;
  returned: bigint;
}
export interface _SERVICE {
  _initializeAccessControlWithSecret: ActorMethod<[string], undefined>;
  approvePass: ActorMethod<[bigint], undefined>;
  assignCallerUserRole: ActorMethod<[Principal, UserRole], undefined>;
  getAllPasses: ActorMethod<[], GatePass[]>;
  getCallerUserRole: ActorMethod<[], UserRole>;
  getLog: ActorMethod<[], LogEntry[]>;
  getMyPasses: ActorMethod<[], GatePass[]>;
  getPassById: ActorMethod<[bigint], [] | [GatePass]>;
  getStats: ActorMethod<[], Stats>;
  isCallerAdmin: ActorMethod<[], boolean>;
  markExit: ActorMethod<[bigint], undefined>;
  markReturn: ActorMethod<[bigint], undefined>;
  rejectPass: ActorMethod<[bigint, string], undefined>;
  requestPass: ActorMethod<[string, string, string, string, string, string, string, string], bigint>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
