/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    admin: IDL.Null,
    user: IDL.Null,
    guest: IDL.Null,
  });
  const PassStatus = IDL.Variant({
    Pending: IDL.Null,
    Approved: IDL.Null,
    Rejected: IDL.Null,
    Exited: IDL.Null,
    Returned: IDL.Null,
  });
  const GatePass = IDL.Record({
    id: IDL.Nat,
    studentName: IDL.Text,
    studentId: IDL.Text,
    rollNumber: IDL.Text,
    department: IDL.Text,
    purpose: IDL.Text,
    destination: IDL.Text,
    expectedReturnTime: IDL.Text,
    note: IDL.Text,
    status: PassStatus,
    requestedAt: IDL.Int,
    approvedAt: IDL.Opt(IDL.Int),
    exitedAt: IDL.Opt(IDL.Int),
    returnedAt: IDL.Opt(IDL.Int),
    rejectionReason: IDL.Opt(IDL.Text),
    requester: IDL.Principal,
  });
  const LogEntry = IDL.Record({
    passId: IDL.Nat,
    studentName: IDL.Text,
    rollNumber: IDL.Text,
    action: IDL.Text,
    timestamp: IDL.Int,
  });
  const Stats = IDL.Record({
    total: IDL.Nat,
    pending: IDL.Nat,
    approved: IDL.Nat,
    rejected: IDL.Nat,
    exited: IDL.Nat,
    returned: IDL.Nat,
  });
  return IDL.Service({
    _initializeAccessControlWithSecret: IDL.Func([IDL.Text], [], []),
    approvePass: IDL.Func([IDL.Nat], [], []),
    assignCallerUserRole: IDL.Func([IDL.Principal, UserRole], [], []),
    getAllPasses: IDL.Func([], [IDL.Vec(GatePass)], ['query']),
    getCallerUserRole: IDL.Func([], [UserRole], ['query']),
    getLog: IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    getMyPasses: IDL.Func([], [IDL.Vec(GatePass)], ['query']),
    getPassById: IDL.Func([IDL.Nat], [IDL.Opt(GatePass)], ['query']),
    getStats: IDL.Func([], [Stats], ['query']),
    isCallerAdmin: IDL.Func([], [IDL.Bool], ['query']),
    markExit: IDL.Func([IDL.Nat], [], []),
    markReturn: IDL.Func([IDL.Nat], [], []),
    rejectPass: IDL.Func([IDL.Nat, IDL.Text], [], []),
    requestPass: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};
export const idlInitArgs = [];
export const init = ({ IDL }) => idlInitArgs;
