/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return { __kind__: "Some", value: value };
}
function none(): None {
    return { __kind__: "None" };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) { throw new Error("unwrap: none"); }
    return option.value;
}
function candid_some<T>(value: T): [T] { return [value]; }
function candid_none<T>(): [] { return []; }
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}

export type PassStatus = "Pending" | "Approved" | "Rejected" | "Exited" | "Returned";
export type UserRole = "admin" | "user" | "guest";

export interface GatePass {
    id: bigint;
    studentName: string;
    studentId: string;
    rollNumber: string;
    department: string;
    purpose: string;
    destination: string;
    expectedReturnTime: string;
    note: string;
    status: PassStatus;
    requestedAt: bigint;
    approvedAt: Option<bigint>;
    exitedAt: Option<bigint>;
    returnedAt: Option<bigint>;
    rejectionReason: Option<string>;
    requester: Principal;
}

export interface LogEntry {
    passId: bigint;
    studentName: string;
    rollNumber: string;
    action: string;
    timestamp: bigint;
}

export interface Stats {
    total: bigint;
    pending: bigint;
    approved: bigint;
    rejected: bigint;
    exited: bigint;
    returned: bigint;
}

function decodePassStatus(s: any): PassStatus {
    if ('Pending' in s) return 'Pending';
    if ('Approved' in s) return 'Approved';
    if ('Rejected' in s) return 'Rejected';
    if ('Exited' in s) return 'Exited';
    return 'Returned';
}

function decodeUserRole(r: any): UserRole {
    if ('admin' in r) return 'admin';
    if ('user' in r) return 'user';
    return 'guest';
}

function decodeOpt<T>(arr: [] | [T]): Option<T> {
    if (arr.length === 0) return none();
    return some(arr[0]);
}

function decodeGatePass(p: any): GatePass {
    return {
        id: p.id,
        studentName: p.studentName,
        studentId: p.studentId,
        rollNumber: p.rollNumber,
        department: p.department,
        purpose: p.purpose,
        destination: p.destination,
        expectedReturnTime: p.expectedReturnTime,
        note: p.note,
        status: decodePassStatus(p.status),
        requestedAt: p.requestedAt,
        approvedAt: decodeOpt(p.approvedAt),
        exitedAt: decodeOpt(p.exitedAt),
        returnedAt: decodeOpt(p.returnedAt),
        rejectionReason: decodeOpt(p.rejectionReason),
        requester: p.requester,
    };
}

export interface backendInterface {
    initializeAccessControl(secret: string): Promise<void>;
    approvePass(id: bigint): Promise<void>;
    rejectPass(id: bigint, reason: string): Promise<void>;
    markExit(id: bigint): Promise<void>;
    markReturn(id: bigint): Promise<void>;
    requestPass(studentName: string, studentId: string, rollNumber: string, department: string, purpose: string, destination: string, expectedReturnTime: string, note: string): Promise<bigint>;
    getAllPasses(): Promise<GatePass[]>;
    getMyPasses(): Promise<GatePass[]>;
    getPassById(id: bigint): Promise<Option<GatePass>>;
    getLog(): Promise<LogEntry[]>;
    getStats(): Promise<Stats>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
}

export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null) {
        if (blob) { this._blob = blob; }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob { return new ExternalBlob(url, null); }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([new Uint8Array(blob)], { type: 'application/octet-stream' }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) { return this._blob; }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string { return this.directURL; }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export class Backend implements backendInterface {
    constructor(
        private actor: ActorSubclass<_SERVICE>,
        private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
        private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
        private processError?: (error: unknown) => never
    ) {}

    async initializeAccessControl(secret: string): Promise<void> {
        await this.actor._initializeAccessControlWithSecret(secret);
    }
    async approvePass(id: bigint): Promise<void> {
        await this.actor.approvePass(id);
    }
    async rejectPass(id: bigint, reason: string): Promise<void> {
        await this.actor.rejectPass(id, reason);
    }
    async markExit(id: bigint): Promise<void> {
        await this.actor.markExit(id);
    }
    async markReturn(id: bigint): Promise<void> {
        await this.actor.markReturn(id);
    }
    async requestPass(studentName: string, studentId: string, rollNumber: string, department: string, purpose: string, destination: string, expectedReturnTime: string, note: string): Promise<bigint> {
        return await this.actor.requestPass(studentName, studentId, rollNumber, department, purpose, destination, expectedReturnTime, note);
    }
    async getAllPasses(): Promise<GatePass[]> {
        const result = await this.actor.getAllPasses();
        return result.map(decodeGatePass);
    }
    async getMyPasses(): Promise<GatePass[]> {
        const result = await this.actor.getMyPasses();
        return result.map(decodeGatePass);
    }
    async getPassById(id: bigint): Promise<Option<GatePass>> {
        const result = await this.actor.getPassById(id);
        if (result.length === 0) return none();
        return some(decodeGatePass(result[0]));
    }
    async getLog(): Promise<LogEntry[]> {
        const result = await this.actor.getLog();
        return result.map((l: any) => ({
            passId: l.passId,
            studentName: l.studentName,
            rollNumber: l.rollNumber,
            action: l.action,
            timestamp: l.timestamp,
        }));
    }
    async getStats(): Promise<Stats> {
        const result = await this.actor.getStats();
        return {
            total: result.total,
            pending: result.pending,
            approved: result.approved,
            rejected: result.rejected,
            exited: result.exited,
            returned: result.returned,
        };
    }
    async getCallerUserRole(): Promise<UserRole> {
        const result = await this.actor.getCallerUserRole();
        return decodeUserRole(result);
    }
    async isCallerAdmin(): Promise<boolean> {
        return await this.actor.isCallerAdmin();
    }
    async assignRole(user: Principal, role: UserRole): Promise<void> {
        const candidRole = role === 'admin' ? { admin: null } : role === 'user' ? { user: null } : { guest: null };
        await this.actor.assignCallerUserRole(user, candidRole);
    }
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({ ...options.agentOptions });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
